/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package perangantariksa;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import static perangantariksa.GamePanel.score;

/**
 *
 * @author NanK
 */
public class highscore extends javax.swing.JFrame {

    /**
     * Creates new form highscore
     */
    public highscore() {
        initComponents();
         this.setLocationRelativeTo(null);
        try {
                    Statement s=koneksi.conn.createStatement();
                    String query="select * from player order by score ASC";
                    
                    ResultSet res   = s.executeQuery(query);

                    
                    while(res.next ()){
                Object[ ] obj = new Object[2];
                obj[0] = res.getString("nama"); 
                obj[1] = res.getString("score");
                   nama1.setText((String) obj[0]); 
                    score.setText((String) obj[1]); 
                    }
                
                } catch (SQLException ex) {
                    java.util.logging.Logger.getLogger(GamePanel.class.getName()).log(Level.SEVERE, null, ex);
                     }
                   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        score = new javax.swing.JLabel();
        nama1 = new javax.swing.JLabel();
        fieldnya1 = new javax.swing.JLabel();
        fieldnya = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 800));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("SPACECRAFT", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("HIGH SCORE");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(220, -30, 410, 190);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/back.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 646, 100, 100);

        score.setFont(new java.awt.Font("Star Jedi", 0, 36)); // NOI18N
        score.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(score);
        score.setBounds(320, 210, 340, 50);

        nama1.setFont(new java.awt.Font("Star Jedi", 0, 36)); // NOI18N
        nama1.setForeground(new java.awt.Color(255, 255, 255));
        nama1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        getContentPane().add(nama1);
        nama1.setBounds(10, 210, 220, 60);

        fieldnya1.setFont(new java.awt.Font("Star Jedi", 0, 48)); // NOI18N
        fieldnya1.setForeground(new java.awt.Color(255, 255, 255));
        fieldnya1.setText("Score");
        getContentPane().add(fieldnya1);
        fieldnya1.setBounds(320, 150, 260, 60);

        fieldnya.setFont(new java.awt.Font("Star Jedi", 0, 48)); // NOI18N
        fieldnya.setForeground(new java.awt.Color(255, 255, 255));
        fieldnya.setText("Nama");
        getContentPane().add(fieldnya);
        fieldnya.setBounds(50, 150, 180, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/skorpage.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 810, 800);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        new Menu().setVisible(true);
        Menu.close();
        dispose();
    }//GEN-LAST:event_jLabel3MouseClicked
   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(highscore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(highscore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(highscore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(highscore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new highscore().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fieldnya;
    private javax.swing.JLabel fieldnya1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel nama1;
    private javax.swing.JLabel score;
    // End of variables declaration//GEN-END:variables
}
