/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package perangantariksa;

import java.io.BufferedInputStream;
import java.io.FileInputStream;
import javazoom.jl.player.Player;//librari yg dibutuhkan buat backsound
import java.sql.SQLException;
import java.util.logging.Level;
import javax.swing.JOptionPane;
//import javazoom.jl.player.Player;

/**
 *
 * @author NanK
 */
public class Menu extends javax.swing.JFrame {

   
    
   
    public Menu() {
       
        initComponents();
        this.setLocationRelativeTo(null);
        play();
        koneksi db=new koneksi();
        try {
            db.konek();
            System.out.println("Berhasil");
            
        } catch (ClassNotFoundException | SQLException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
         
    }
  
    private static String filename;
    private static Player nank;
    
// buat naruh backsound    
public static void play() {
        try {
            FileInputStream fis     = new FileInputStream("sounds/backsound.mp3");
            BufferedInputStream bis = new BufferedInputStream(fis);
            nank = new Player(bis);
        }
        catch (Exception e) {
            System.out.println("ada masalah? " + filename);
            System.out.println(e);
        }

        // mainkan backsound dengan thread
        new Thread() {
            @Override
            public void run() {
                try { nank.play();
                     

                }
                catch (Exception e) { System.out.println(e); }
            }
        }.start();

    }

    public static void close()
       {
           nank.close();
           
       }
    
    public void doExit() {
        int confirm = JOptionPane.showConfirmDialog(this,
                "Yakin Keluar Dari Game Sekarang",
                "Perang Antariksa",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);

        if (confirm == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        play = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        help = new javax.swing.JLabel();
        hc = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 800));
        setUndecorated(true);
        getContentPane().setLayout(null);

        play.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/playbutton.png"))); // NOI18N
        play.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                playMouseClicked(evt);
            }
        });
        getContentPane().add(play);
        play.setBounds(260, 260, 320, 130);

        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/exitbutton.png"))); // NOI18N
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        getContentPane().add(exit);
        exit.setBounds(260, 620, 300, 90);

        help.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/hellpbutton.png"))); // NOI18N
        help.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                helpMouseClicked(evt);
            }
        });
        getContentPane().add(help);
        help.setBounds(260, 490, 330, 120);

        hc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/HIGHSCORE.png"))); // NOI18N
        hc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hcMouseClicked(evt);
            }
        });
        getContentPane().add(hc);
        hc.setBounds(260, 360, 320, 160);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menu.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -190, 800, 1180);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void playMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playMouseClicked
        new PlayFrame().setVisible(true);
      
    }//GEN-LAST:event_playMouseClicked

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        
    }//GEN-LAST:event_exitMouseClicked

    private void helpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_helpMouseClicked
        new help().setVisible(true);
        dispose();
    }//GEN-LAST:event_helpMouseClicked

    private void hcMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hcMouseClicked
            new highscore().setVisible(true);//buat manggil frame highscore
            dispose();    // buat nutup frame sebelumnya    
    }//GEN-LAST:event_hcMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel exit;
    private javax.swing.JLabel hc;
    private javax.swing.JLabel help;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel play;
    // End of variables declaration//GEN-END:variables
}
